-- Fix refractive_profiles table - Add missing columns
-- إصلاح جدول refractive_profiles - إضافة الأعمدة الناقصة

ALTER TABLE `refractive_profiles`
  ADD COLUMN `patient_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `operation_id`,
  ADD COLUMN `patient_age` int DEFAULT NULL AFTER `patient_name`,
  ADD COLUMN `optometrist` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `patient_age`,
  ADD COLUMN `eyeglasses_age` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `optometrist`,
  ADD COLUMN `time_with_current_rx` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `eyeglasses_age`,
  ADD COLUMN `current_eyeglasses_od_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `time_with_current_rx`,
  ADD COLUMN `current_eyeglasses_od_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_od_sphere`,
  ADD COLUMN `current_eyeglasses_od_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_od_cylinder`,
  ADD COLUMN `current_eyeglasses_od_vision` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_od_axis`,
  ADD COLUMN `current_eyeglasses_os_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_od_vision`,
  ADD COLUMN `current_eyeglasses_os_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_os_sphere`,
  ADD COLUMN `current_eyeglasses_os_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_os_cylinder`,
  ADD COLUMN `current_eyeglasses_os_vision` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_os_axis`,
  ADD COLUMN `contact_lenses` enum('No','Soft','Hard') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `current_eyeglasses_os_vision`,
  ADD COLUMN `time_without_lenses` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `contact_lenses`,
  ADD COLUMN `manifest_refraction_od_udva` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `time_without_lenses`,
  ADD COLUMN `manifest_refraction_od_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_udva`,
  ADD COLUMN `manifest_refraction_od_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_sphere`,
  ADD COLUMN `manifest_refraction_od_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_cylinder`,
  ADD COLUMN `manifest_refraction_od_bscva` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_axis`,
  ADD COLUMN `manifest_refraction_od_dcnva_40cm` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_bscva`,
  ADD COLUMN `manifest_refraction_od_add_j1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_dcnva_40cm`,
  ADD COLUMN `manifest_refraction_od_rg` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_add_j1`,
  ADD COLUMN `manifest_refraction_os_udva` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_od_rg`,
  ADD COLUMN `manifest_refraction_os_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_udva`,
  ADD COLUMN `manifest_refraction_os_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_sphere`,
  ADD COLUMN `manifest_refraction_os_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_cylinder`,
  ADD COLUMN `manifest_refraction_os_bscva` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_axis`,
  ADD COLUMN `manifest_refraction_os_dcnva_40cm` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_bscva`,
  ADD COLUMN `manifest_refraction_os_add_j1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_dcnva_40cm`,
  ADD COLUMN `manifest_refraction_os_rg` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_add_j1`,
  ADD COLUMN `refraction_after_dilation_od_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `manifest_refraction_os_rg`,
  ADD COLUMN `refraction_after_dilation_od_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_od_sphere`,
  ADD COLUMN `refraction_after_dilation_od_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_od_cylinder`,
  ADD COLUMN `refraction_after_dilation_od_vision` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_od_axis`,
  ADD COLUMN `refraction_after_dilation_os_sphere` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_od_vision`,
  ADD COLUMN `refraction_after_dilation_os_cylinder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_os_sphere`,
  ADD COLUMN `refraction_after_dilation_os_axis` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_os_cylinder`,
  ADD COLUMN `refraction_after_dilation_os_vision` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_os_axis`,
  ADD COLUMN `refraction_after_dilation_type` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_os_vision`,
  ADD COLUMN `pupil_diameter_od_mesopic` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `refraction_after_dilation_type`,
  ADD COLUMN `pupil_diameter_od_scotopic` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `pupil_diameter_od_mesopic`,
  ADD COLUMN `pupil_diameter_os_mesopic` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `pupil_diameter_od_scotopic`,
  ADD COLUMN `pupil_diameter_os_scotopic` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `pupil_diameter_os_mesopic`,
  ADD COLUMN `dominant_eye` enum('OD','OS') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `pupil_diameter_os_scotopic`,
  ADD COLUMN `simulation_for_monovision` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `dominant_eye`,
  ADD COLUMN `notes` text COLLATE utf8mb4_general_ci AFTER `simulation_for_monovision`;
