-- Fix operation_notes table - Add missing columns
-- This script adds all missing columns to the operation_notes table
-- Note: MySQL doesn't support IF NOT EXISTS with ADD COLUMN, so run this only once
-- If you get "Duplicate column name" errors, the columns already exist and you can ignore them

ALTER TABLE `operation_notes`
  ADD COLUMN `operation_type` enum('PRK','Femto-LASIK','SMILE','PTK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `doctor_id`,
  ADD COLUMN `operation_type_od` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `operation_type`,
  ADD COLUMN `operation_type_os` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `operation_type_od`,
  ADD COLUMN `same_operation_type_both_eyes` tinyint(1) NOT NULL DEFAULT '0' AFTER `operation_type_os`,
  ADD COLUMN `operation_eye` enum('OD','OS','OU') COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OU' AFTER `same_operation_type_both_eyes`,
  ADD COLUMN `monovision_eye` enum('none','OD','OS') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `operation_eye`,
  ADD COLUMN `eye_drops_vigamox` tinyint(1) NOT NULL DEFAULT '0' AFTER `monovision_eye`,
  ADD COLUMN `eye_drops_pred_forte` tinyint(1) NOT NULL DEFAULT '0' AFTER `eye_drops_vigamox`,
  ADD COLUMN `eye_drops_other` tinyint(1) NOT NULL DEFAULT '0' AFTER `eye_drops_pred_forte`,
  ADD COLUMN `eye_drops_other_details` text COLLATE utf8mb4_general_ci AFTER `eye_drops_other`,
  ADD COLUMN `prk_epithelial_removal` enum('Alcohol','Mechanical','Trans-PRK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `eye_drops_other_details`,
  ADD COLUMN `prk_excimer_profile` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_epithelial_removal`,
  ADD COLUMN `prk_mmc_0_02_percent` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_excimer_profile`,
  ADD COLUMN `prk_bandage_contact_lens` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_mmc_0_02_percent`,
  ADD COLUMN `prk_epithelial_removal_od` enum('Alcohol','Mechanical','Trans-PRK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_bandage_contact_lens`,
  ADD COLUMN `prk_epithelial_removal_os` enum('Alcohol','Mechanical','Trans-PRK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_epithelial_removal_od`,
  ADD COLUMN `prk_excimer_profile_od` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_epithelial_removal_os`,
  ADD COLUMN `prk_excimer_profile_os` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_excimer_profile_od`,
  ADD COLUMN `prk_mmc_0_02_percent_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_excimer_profile_os`,
  ADD COLUMN `prk_mmc_0_02_percent_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_mmc_0_02_percent_od`,
  ADD COLUMN `prk_bandage_contact_lens_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_mmc_0_02_percent_os`,
  ADD COLUMN `prk_bandage_contact_lens_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `prk_bandage_contact_lens_od`,
  ADD COLUMN `prk_target_od` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_bandage_contact_lens_os`,
  ADD COLUMN `prk_target_os` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `prk_target_od`,
  ADD COLUMN `femto_flap_done` tinyint(1) DEFAULT NULL AFTER `prk_target_os`,
  ADD COLUMN `femto_excimer_profile` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `femto_flap_done`,
  ADD COLUMN `femto_bandage_contact_lens` tinyint(1) NOT NULL DEFAULT '0' AFTER `femto_excimer_profile`,
  ADD COLUMN `femto_flap_done_od` tinyint(1) DEFAULT NULL AFTER `femto_bandage_contact_lens`,
  ADD COLUMN `femto_flap_done_os` tinyint(1) DEFAULT NULL AFTER `femto_flap_done_od`,
  ADD COLUMN `femto_excimer_profile_od` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `femto_flap_done_os`,
  ADD COLUMN `femto_excimer_profile_os` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `femto_excimer_profile_od`,
  ADD COLUMN `femto_bandage_contact_lens_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `femto_excimer_profile_os`,
  ADD COLUMN `femto_bandage_contact_lens_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `femto_bandage_contact_lens_od`,
  ADD COLUMN `femto_target_od` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `femto_bandage_contact_lens_os`,
  ADD COLUMN `femto_target_os` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `femto_target_od`,
  ADD COLUMN `smile_complete_lenticule_separation` tinyint(1) DEFAULT NULL AFTER `femto_target_os`,
  ADD COLUMN `smile_complete_lenticule_extraction` tinyint(1) DEFAULT NULL AFTER `smile_complete_lenticule_separation`,
  ADD COLUMN `smile_complete_lenticule_separation_od` tinyint(1) DEFAULT NULL AFTER `smile_complete_lenticule_extraction`,
  ADD COLUMN `smile_complete_lenticule_separation_os` tinyint(1) DEFAULT NULL AFTER `smile_complete_lenticule_separation_od`,
  ADD COLUMN `smile_complete_lenticule_extraction_od` tinyint(1) DEFAULT NULL AFTER `smile_complete_lenticule_separation_os`,
  ADD COLUMN `smile_complete_lenticule_extraction_os` tinyint(1) DEFAULT NULL AFTER `smile_complete_lenticule_extraction_od`,
  ADD COLUMN `smile_target_od` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `smile_complete_lenticule_extraction_os`,
  ADD COLUMN `smile_target_os` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `smile_target_od`,
  ADD COLUMN `ptk_excimer_profile` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `smile_target_os`,
  ADD COLUMN `ptk_epithelial_removal` enum('Alcohol','Mechanical','Trans-PTK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_excimer_profile`,
  ADD COLUMN `ptk_mmc_0_02_percent` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_epithelial_removal`,
  ADD COLUMN `ptk_bandage_contact_lens` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_mmc_0_02_percent`,
  ADD COLUMN `ptk_epithelial_removal_od` enum('Alcohol','Mechanical','Trans-PTK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_bandage_contact_lens`,
  ADD COLUMN `ptk_epithelial_removal_os` enum('Alcohol','Mechanical','Trans-PTK') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_epithelial_removal_od`,
  ADD COLUMN `ptk_excimer_profile_od` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_epithelial_removal_os`,
  ADD COLUMN `ptk_excimer_profile_os` enum('Aspheric Front','Topography-guided') COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_excimer_profile_od`,
  ADD COLUMN `ptk_mmc_0_02_percent_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_excimer_profile_os`,
  ADD COLUMN `ptk_mmc_0_02_percent_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_mmc_0_02_percent_od`,
  ADD COLUMN `ptk_bandage_contact_lens_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_mmc_0_02_percent_os`,
  ADD COLUMN `ptk_bandage_contact_lens_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_bandage_contact_lens_od`,
  ADD COLUMN `ptk_target_od` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_bandage_contact_lens_os`,
  ADD COLUMN `ptk_target_os` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL AFTER `ptk_target_od`,
  ADD COLUMN `mmc_0_02_percent_od` tinyint(1) NOT NULL DEFAULT '0' AFTER `ptk_target_os`,
  ADD COLUMN `mmc_duration_sec_od` int DEFAULT NULL AFTER `mmc_0_02_percent_od`,
  ADD COLUMN `mmc_0_02_percent_os` tinyint(1) NOT NULL DEFAULT '0' AFTER `mmc_duration_sec_od`,
  ADD COLUMN `mmc_duration_sec_os` int DEFAULT NULL AFTER `mmc_0_02_percent_os`,
  ADD COLUMN `notes` text COLLATE utf8mb4_general_ci AFTER `mmc_duration_sec_os`;

-- Add index for operation_type
ALTER TABLE `operation_notes` ADD INDEX `operation_notes_operation_type_index` (`operation_type`);
