PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_12_08_085741_create_patients_table',1);
INSERT INTO migrations VALUES(5,'2025_12_08_104139_create_categories_table',1);
INSERT INTO migrations VALUES(6,'2025_12_08_104145_create_doctors_table',1);
INSERT INTO migrations VALUES(7,'2025_12_08_104149_create_procedures_table',1);
INSERT INTO migrations VALUES(8,'2025_12_08_104150_create_appointments_table',1);
INSERT INTO migrations VALUES(9,'2025_12_08_105608_add_id_number_to_patients_table',1);
INSERT INTO migrations VALUES(10,'2025_12_08_111647_add_role_and_branch_to_users_table',1);
INSERT INTO migrations VALUES(11,'2025_12_08_111650_create_branches_table',1);
INSERT INTO migrations VALUES(12,'2025_12_08_111654_add_user_id_and_branch_id_to_doctors_table',1);
INSERT INTO migrations VALUES(13,'2025_12_08_111656_add_created_by_and_branch_id_to_appointments_table',1);
INSERT INTO migrations VALUES(14,'2025_12_08_132848_add_photo_to_doctors_table',1);
INSERT INTO migrations VALUES(15,'2025_12_08_132850_create_invoices_table',1);
INSERT INTO migrations VALUES(16,'2025_12_08_135318_add_visit_stage_to_appointments_table',1);
INSERT INTO migrations VALUES(17,'2025_12_08_155010_create_operations_table',1);
INSERT INTO migrations VALUES(18,'2025_12_08_155813_create_refractive_profiles_table',1);
INSERT INTO migrations VALUES(19,'2025_12_08_155814_create_medical_histories_table',1);
INSERT INTO migrations VALUES(20,'2025_12_08_155815_create_eye_examinations_table',1);
INSERT INTO migrations VALUES(21,'2025_12_08_155816_create_ectasia_risk_assessments_table',1);
INSERT INTO migrations VALUES(22,'2025_12_08_155817_create_operation_details_table',1);
INSERT INTO migrations VALUES(23,'2025_12_08_155818_create_operation_approvals_table',1);
INSERT INTO migrations VALUES(24,'2025_12_08_155820_add_operation_id_to_appointments_table',1);
INSERT INTO migrations VALUES(25,'2025_12_08_155821_add_operation_id_to_invoices_table',1);
INSERT INTO migrations VALUES(26,'2025_12_10_175913_drop_operation_files_table',1);
INSERT INTO migrations VALUES(27,'2025_12_10_180434_add_missing_fields_to_refractive_profiles_table',1);
INSERT INTO migrations VALUES(28,'2025_12_10_180436_add_missing_fields_to_eye_examinations_table',1);
INSERT INTO migrations VALUES(29,'2025_12_10_180438_add_missing_fields_to_ectasia_risk_assessments_table',1);
INSERT INTO migrations VALUES(30,'2025_12_10_180440_add_missing_fields_to_operations_table',1);
INSERT INTO migrations VALUES(31,'2025_12_10_182629_add_pre_op_target_fields_to_operation_details_table',1);
INSERT INTO migrations VALUES(32,'2025_12_10_182631_add_surgeon_correction_fields_to_refractive_profiles_table',1);
INSERT INTO migrations VALUES(33,'2025_12_14_100918_add_occupation_to_patients_table',1);
INSERT INTO migrations VALUES(34,'2025_12_14_101306_remove_country_from_patients_table',1);
INSERT INTO migrations VALUES(35,'2025_12_14_102207_remove_target_parameters_from_operation_details_table',1);
INSERT INTO migrations VALUES(36,'2025_12_14_115132_add_visit_type_to_appointments_table',1);
INSERT INTO migrations VALUES(37,'2025_12_14_120219_add_photo_to_patients_table',1);
INSERT INTO migrations VALUES(38,'2025_12_14_120823_remove_photo_from_patients_table',1);
INSERT INTO migrations VALUES(39,'2025_12_14_121250_add_price_to_appointments_table',1);
INSERT INTO migrations VALUES(40,'2025_12_14_121250_add_price_to_categories_table',1);
INSERT INTO migrations VALUES(41,'2025_12_14_132504_remove_cycloplegic_refraction_from_refractive_profiles_table',1);
INSERT INTO migrations VALUES(42,'2025_12_14_133125_add_refraction_after_dilation_type_to_refractive_profiles_table',1);
INSERT INTO migrations VALUES(43,'2025_12_14_134157_remove_surgeon_correction_from_refractive_profiles_table',1);
INSERT INTO migrations VALUES(44,'2025_12_14_134604_add_pupil_diameter_to_refractive_profiles_table',1);
INSERT INTO migrations VALUES(45,'2025_12_14_171809_change_refractive_profiles_fields_to_string',1);
INSERT INTO migrations VALUES(46,'2025_12_14_172144_change_refraction_stable_1year_default_to_true',1);
INSERT INTO migrations VALUES(47,'2025_12_14_172951_add_yes_fields_to_medical_histories_table',1);
INSERT INTO migrations VALUES(48,'2025_12_14_184545_update_tomography_status_enum_to_include_not_normal',1);
INSERT INTO migrations VALUES(49,'2025_12_14_190845_remove_treatment_options_from_operations_table',1);
INSERT INTO migrations VALUES(50,'2025_12_14_191902_remove_patient_teaching_and_comments_from_operations_table',1);
INSERT INTO migrations VALUES(51,'2025_12_14_192236_create_operation_files_table',1);
INSERT INTO migrations VALUES(52,'2025_12_15_000001_add_decision_fields_to_operations_table',1);
INSERT INTO migrations VALUES(53,'2025_12_15_082927_add_appointment_id_to_operations_table',1);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('ryh282N7CH7mUnv46uHD06fFIqshtFiFpxSmPd5i',NULL,'127.0.0.1','curl/8.7.1','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiUUZuVVE3ZmF6cnlkT2FXUDdPYVByd2RqMHJtTGlOVm83bTFXRmNvQiI7czozOiJ1cmwiO2E6MTp7czo4OiJpbnRlbmRlZCI7czoyMToiaHR0cDovLzEyNy4wLjAuMTo4MDAwIjt9czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=',1768029200);
INSERT INTO sessions VALUES('1NTS34PsQv4bWFhBFOEK2eObH19hsHjfum3ORBlD',NULL,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36','YTozOntzOjY6Il90b2tlbiI7czo0MDoiS3NhcHFSbHZpQmYxakhMcHRrd0xJUG16YkxSMWtCN0JJN21naWFROCI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6Mjc6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9sb2dpbiI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fX0=',1768029285);
INSERT INTO sessions VALUES('HRCJCuMmJ1R1zGUEiEvi9zZ6DYZIEJV9BCy2tUIA',1,'127.0.0.1','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cursor/2.3.29 Chrome/138.0.7204.251 Electron/37.7.0 Safari/537.36','YTo1OntzOjY6Il90b2tlbiI7czo0MDoidXhJRVJxU3p6cGNoTE5VWUl4cjhkRjVqbWpEeEoxNGxuTFROY2RZeiI7czozOiJ1cmwiO2E6MTp7czo4OiJpbnRlbmRlZCI7czoyMToiaHR0cDovLzEyNy4wLjAuMTo4MDAwIjt9czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjE7fQ==',1768029395);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "patients" ("id" integer primary key autoincrement not null, "full_name" varchar not null, "date_of_birth" date, "gender" varchar check ("gender" in ('male', 'female')), "phone" varchar, "phone_secondary" varchar, "city" varchar, "notes" text, "created_at" datetime, "updated_at" datetime, "id_number" varchar, "occupation" varchar);
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime, "price" numeric default '0');
CREATE TABLE IF NOT EXISTS "procedures" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "default_duration" integer not null default '30', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "branches" ("id" integer primary key autoincrement not null, "name" varchar not null, "address" varchar, "phone" varchar, "email" varchar, "notes" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role" varchar not null default ('secretary'), "is_active" tinyint(1) not null default ('1'), "branch_id" integer, foreign key("branch_id") references "branches"("id") on delete set null);
INSERT INTO users VALUES(1,'Test User','test@example.com',NULL,'$2y$12$ucFILdfMqc6GuBM0fmCOJe6UtqdsVSL3hHW7AC9CR4VX.9P3h4uFy','2ZgeYikG82J0XqTz0pXquAersIlYp7uG8w9vDzS2Sd7Hzp3IK7vmA13lTmxq','2026-01-10 07:07:24','2026-01-10 07:15:56','admin',1,NULL);
CREATE TABLE IF NOT EXISTS "doctors" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar, "phone" varchar, "specialization" varchar, "notify_via_sms" tinyint(1) not null default ('0'), "notify_via_email" tinyint(1) not null default ('0'), "follow_up" tinyint(1) not null default ('0'), "created_at" datetime, "updated_at" datetime, "user_id" integer, "branch_id" integer, "photo" varchar, foreign key("user_id") references "users"("id") on delete set null, foreign key("branch_id") references "branches"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "eye_examinations" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "examination_type" varchar check ("examination_type" in ('pre_op', 'post_op')) not null default 'pre_op', "od_lids" varchar, "od_conjunctiva" varchar, "od_cornea" varchar, "od_tbut" varchar, "od_schirmer" varchar, "od_anterior_chamber" varchar, "od_iris_pupil" varchar, "od_lens" varchar, "od_vitreous" varchar, "od_optic_disc" varchar, "od_retina" varchar, "od_macula" varchar, "od_vessels" varchar, "od_fom" varchar, "od_findings" text, "os_lids" varchar, "os_conjunctiva" varchar, "os_cornea" varchar, "os_tbut" varchar, "os_schirmer" varchar, "os_anterior_chamber" varchar, "os_iris_pupil" varchar, "os_lens" varchar, "os_vitreous" varchar, "os_optic_disc" varchar, "os_retina" varchar, "os_macula" varchar, "os_vessels" varchar, "os_fom" varchar, "os_findings" text, "unaided_od" varchar, "unaided_os" varchar, "manifest_refraction_od" text, "manifest_refraction_os" text, "cyclo_refraction_od" text, "cyclo_refraction_os" text, "notes" text, "created_at" datetime, "updated_at" datetime, "od_iop" varchar, "os_iop" varchar, foreign key("operation_id") references "operations"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "ectasia_risk_assessments" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "pta_percentage_od" numeric, "pta_percentage_os" numeric, "rsb_od" numeric, "rsb_os" numeric, "tomography_normal_pattern" tinyint(1) not null default '0', "tomography_other" text, "pachymetry_thinnest_od" integer, "pachymetry_thinnest_os" integer, "notes" text, "created_at" datetime, "updated_at" datetime, "tomography_status" varchar check ("tomography_status" in ('normal', 'suspicious', 'other')), foreign key("operation_id") references "operations"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "operation_details" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "femto_lasik" tinyint(1) not null default '0', "prk_mmc" tinyint(1) not null default '0', "prk_type" varchar check ("prk_type" in ('Alcohol 20%', 'Trans-PRK', 'Brush')), "trans_prk" tinyint(1) not null default '0', "ptk" tinyint(1) not null default '0', "topography_guided" tinyint(1) not null default '0', "excimer_profile" varchar check ("excimer_profile" in ('WFO', 'Topography Guided', 'Custom', 'Other')), "mmc_concentration" numeric, "mmc_duration_seconds" integer, "bll" tinyint(1) not null default '0', "drops_used" text, "target_refraction_od" text, "target_refraction_os" text, "mv_eye" varchar, "has_complications" tinyint(1) not null default '0', "complications_details" text, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("operation_id") references "operations"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "operation_approvals" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "approved_by" integer not null, "approval_type" varchar check ("approval_type" in ('medical_clearance', 'surgical_approval', 'anesthesia_approval', 'final_approval')) not null default 'medical_clearance', "status" varchar check ("status" in ('pending', 'approved', 'rejected')) not null default 'pending', "comments" text, "approval_date" date, "created_at" datetime, "updated_at" datetime, foreign key("operation_id") references "operations"("id") on delete cascade, foreign key("approved_by") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "appointments" ("id" integer primary key autoincrement not null, "patient_id" integer not null, "doctor_id" integer not null, "category_id" integer, "procedure_id" integer, "appointment_date" date not null, "appointment_time" time not null, "duration" integer not null default ('30'), "notes" text, "notify_patient_sms" tinyint(1) not null default ('0'), "notify_doctor_sms" tinyint(1) not null default ('0'), "notify_doctor_email" tinyint(1) not null default ('0'), "follow_up" tinyint(1) not null default ('0'), "status" varchar not null default ('scheduled'), "created_at" datetime, "updated_at" datetime, "created_by" integer, "branch_id" integer, "visit_stage" varchar, "visit_type" varchar, "operation_id" integer, "price" numeric default '0', foreign key("branch_id") references branches("id") on delete set null on update no action, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("patient_id") references patients("id") on delete cascade on update no action, foreign key("doctor_id") references doctors("id") on delete cascade on update no action, foreign key("category_id") references categories("id") on delete set null on update no action, foreign key("procedure_id") references procedures("id") on delete set null on update no action, foreign key("operation_id") references "operations"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "invoices" ("id" integer primary key autoincrement not null, "invoice_number" varchar not null, "patient_id" integer not null, "appointment_id" integer, "doctor_id" integer, "branch_id" integer, "invoice_date" date not null, "due_date" date, "subtotal" numeric not null default ('0'), "discount" numeric not null default ('0'), "tax" numeric not null default ('0'), "total_amount" numeric not null default ('0'), "paid_amount" numeric not null default ('0'), "remaining_amount" numeric not null default ('0'), "status" varchar not null default ('pending'), "payment_method" varchar, "notes" text, "created_by" integer, "created_at" datetime, "updated_at" datetime, "operation_id" integer, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("branch_id") references branches("id") on delete set null on update no action, foreign key("doctor_id") references doctors("id") on delete set null on update no action, foreign key("appointment_id") references appointments("id") on delete set null on update no action, foreign key("patient_id") references patients("id") on delete cascade on update no action, foreign key("operation_id") references "operations"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "refractive_profiles" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "patient_name" varchar, "patient_age" integer, "optometrist" varchar, "eyeglasses_age" varchar, "time_with_current_rx" varchar, "current_eyeglasses_od_sphere" varchar, "current_eyeglasses_od_cylinder" varchar, "current_eyeglasses_od_axis" varchar, "current_eyeglasses_od_vision" varchar, "current_eyeglasses_os_sphere" varchar, "current_eyeglasses_os_cylinder" varchar, "current_eyeglasses_os_axis" varchar, "current_eyeglasses_os_vision" varchar, "contact_lenses" varchar, "time_without_lenses" varchar, "manifest_refraction_od_udva" varchar, "manifest_refraction_od_sphere" varchar, "manifest_refraction_od_cylinder" varchar, "manifest_refraction_od_axis" varchar, "manifest_refraction_od_bscva" varchar, "manifest_refraction_od_dcnva_40cm" varchar, "manifest_refraction_od_add_j1" varchar, "manifest_refraction_os_udva" varchar, "manifest_refraction_os_sphere" varchar, "manifest_refraction_os_cylinder" varchar, "manifest_refraction_os_axis" varchar, "manifest_refraction_os_bscva" varchar, "manifest_refraction_os_dcnva_40cm" varchar, "manifest_refraction_os_add_j1" varchar, "refraction_after_dilation_od_sphere" varchar, "refraction_after_dilation_od_cylinder" varchar, "refraction_after_dilation_od_axis" varchar, "refraction_after_dilation_od_vision" varchar, "refraction_after_dilation_os_sphere" varchar, "refraction_after_dilation_os_cylinder" varchar, "refraction_after_dilation_os_axis" varchar, "refraction_after_dilation_os_vision" varchar, "notes" text, "created_at" datetime, "updated_at" datetime, "dominant_eye" varchar, "simulation_for_monovision" varchar, "manifest_refraction_od_rg" varchar, "manifest_refraction_os_rg" varchar, "refraction_after_dilation_type" varchar, "pupil_diameter_od_mesopic" varchar, "pupil_diameter_od_scotopic" varchar, "pupil_diameter_os_mesopic" varchar, "pupil_diameter_os_scotopic" varchar, foreign key("operation_id") references operations("id") on delete cascade on update no action);
CREATE TABLE IF NOT EXISTS "medical_histories" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "diabetes" tinyint(1) not null default ('0'), "chronic_disease" tinyint(1) not null default ('0'), "chronic_disease_details" text, "herpes_keratitis" tinyint(1) not null default ('0'), "glaucoma" tinyint(1) not null default ('0'), "family_history_keratoconus" tinyint(1) not null default ('0'), "eye_rubber" tinyint(1) not null default ('0'), "pregnancy" tinyint(1) not null default ('0'), "ocular_surgery" tinyint(1) not null default ('0'), "ocular_surgery_details" text, "family_history_ocular_disease" text, "current_medications" text, "allergies" text, "glare_halos_squint" tinyint(1) not null default ('0'), "refraction_stable_1year" tinyint(1) not null default '1', "contact_lens_use" tinyint(1) not null default ('0'), "past_medical_history" text, "past_ophthalmic_history" text, "chief_complaint" text, "notes" text, "created_at" datetime, "updated_at" datetime, "family_history_ocular_disease_yes" tinyint(1) not null default '0', "current_medications_yes" tinyint(1) not null default '0', foreign key("operation_id") references operations("id") on delete cascade on update no action);
CREATE TABLE IF NOT EXISTS "operation_files" ("id" integer primary key autoincrement not null, "operation_id" integer not null, "file_path" varchar not null, "file_name" varchar not null, "file_type" varchar, "mime_type" varchar, "file_size" integer, "description" text, "eye" varchar check ("eye" in ('OD', 'OS', 'OU')) not null default 'OU', "created_at" datetime, "updated_at" datetime, foreign key("operation_id") references "operations"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "operations" ("id" integer primary key autoincrement not null, "patient_id" integer not null, "doctor_id" integer not null, "branch_id" integer not null, "created_by" integer not null, "operation_type" varchar not null default ('LASIK'), "operation_eye" varchar not null default ('OU'), "cost" numeric not null default ('0'), "start_date" date, "end_date" date, "status" varchar not null default ('scheduled'), "pre_op_assessment_date" date, "post_op_notes" text, "presbyopia_profile" text, "recommendation_notes" text, "diagnosis" text, "plan" text, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "topographic_guided_profile" varchar, "mv_eye" varchar, "target" varchar, "decision" varchar, "prk_epithelial_removal" varchar, "prk_excimer_profile" varchar, "prk_monovision_eye" varchar, "prk_target" varchar, "femto_excimer_profile" varchar, "femto_monovision" tinyint(1), "smile_monovision" tinyint(1), "ptk_topo_guided" tinyint(1), "incompatible_notes" text, "appointment_id" integer, foreign key("created_by") references users("id") on delete cascade on update no action, foreign key("branch_id") references branches("id") on delete cascade on update no action, foreign key("doctor_id") references doctors("id") on delete cascade on update no action, foreign key("patient_id") references patients("id") on delete cascade on update no action, foreign key("appointment_id") references "appointments"("id") on delete set null);
INSERT INTO sqlite_sequence VALUES('migrations',58);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('doctors',0);
INSERT INTO sqlite_sequence VALUES('appointments',0);
INSERT INTO sqlite_sequence VALUES('invoices',0);
INSERT INTO sqlite_sequence VALUES('refractive_profiles',0);
INSERT INTO sqlite_sequence VALUES('medical_histories',0);
INSERT INTO sqlite_sequence VALUES('operations',0);
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "categories_name_unique" on "categories" ("name");
CREATE UNIQUE INDEX "patients_id_number_unique" on "patients" ("id_number");
CREATE INDEX "branches_is_active_index" on "branches" ("is_active");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "doctors_email_unique" on "doctors" ("email");
CREATE UNIQUE INDEX "doctors_user_id_unique" on "doctors" ("user_id");
CREATE INDEX "eye_examinations_operation_id_index" on "eye_examinations" ("operation_id");
CREATE INDEX "eye_examinations_examination_type_index" on "eye_examinations" ("examination_type");
CREATE INDEX "ectasia_risk_assessments_operation_id_index" on "ectasia_risk_assessments" ("operation_id");
CREATE INDEX "operation_details_operation_id_index" on "operation_details" ("operation_id");
CREATE INDEX "operation_approvals_operation_id_index" on "operation_approvals" ("operation_id");
CREATE INDEX "operation_approvals_approved_by_index" on "operation_approvals" ("approved_by");
CREATE INDEX "operation_approvals_status_index" on "operation_approvals" ("status");
CREATE INDEX "appointments_appointment_date_appointment_time_index" on "appointments" ("appointment_date", "appointment_time");
CREATE INDEX "appointments_branch_id_index" on "appointments" ("branch_id");
CREATE INDEX "appointments_created_by_index" on "appointments" ("created_by");
CREATE INDEX "appointments_doctor_id_index" on "appointments" ("doctor_id");
CREATE INDEX "appointments_patient_id_index" on "appointments" ("patient_id");
CREATE INDEX "appointments_operation_id_index" on "appointments" ("operation_id");
CREATE INDEX "invoices_invoice_date_index" on "invoices" ("invoice_date");
CREATE INDEX "invoices_invoice_number_index" on "invoices" ("invoice_number");
CREATE UNIQUE INDEX "invoices_invoice_number_unique" on "invoices" ("invoice_number");
CREATE INDEX "invoices_patient_id_index" on "invoices" ("patient_id");
CREATE INDEX "invoices_status_index" on "invoices" ("status");
CREATE INDEX "invoices_operation_id_index" on "invoices" ("operation_id");
CREATE INDEX "refractive_profiles_operation_id_index" on "refractive_profiles" ("operation_id");
CREATE INDEX "medical_histories_operation_id_index" on "medical_histories" ("operation_id");
CREATE INDEX "operation_files_operation_id_index" on "operation_files" ("operation_id");
CREATE INDEX "operations_branch_id_index" on "operations" ("branch_id");
CREATE INDEX "operations_doctor_id_index" on "operations" ("doctor_id");
CREATE INDEX "operations_operation_type_index" on "operations" ("operation_type");
CREATE INDEX "operations_patient_id_index" on "operations" ("patient_id");
CREATE INDEX "operations_start_date_index" on "operations" ("start_date");
CREATE INDEX "operations_status_index" on "operations" ("status");
COMMIT;
